### ISSUE TITLE
Issue regarding choosing correct architecture

### ISSUE THREAD

**Issue by VARUN-DEVULAPALLI** [FortyNorthSecurity/EXCELntDonut#8]
Had a question regarding being able to choose the architecture type. It seems that no matter what type of architecture the payload is, the tool will trying compiling both the x86 version and x64 version which causes problems. For example, if I have a x64 based input file, it gives a seg fault when trying to mess with the x86 side of the code. Was just wondering if this was intentional or if I'm missing something. For now, I tried commenting out the x86 related pieces of code which seems to work but again just wanted to double check.

**Comment by ChrisTruncer** [comment]
This is intentional (unless @joeleonjr joins in and corrects me). He's tried to make it so that you can appropriately handle any architecture assuming your code allows for that.

**Comment by coffeegist** [comment]
@VARUN-DEVULAPALLI I had a similar issue, manually installing donut-0.9.3 fixed the segmentation fault issue on my side
