### ISSUE TITLE
-

### ISSUE THREAD

**Issue by FrazHackz** [FortyNorthSecurity/EXCELntDonut#9]

**Comment by ChrisTruncer** [comment]
Hi there, you had closed this and removed everything from the issue. If you had a question, it’s likely others do/did too. Would you mind sharing the problem and what your solution was?

**Comment by FrazHackz** [comment]
Hi Chris!
Im really thankful to you to replying me.
I am working on your tool and thanks much its great tool, but while using
obfuscation its not working , but now i found there was issue in my
payload.
Now its working fine.
Thank you
Kind regards
Fraz Ahmad
